server {
    listen 80;

    access_log /var/log/nginx/mywebapp_access.log;
    error_log /var/log/nginx/mywebapp_error.log;

    location /health {
        proxy_pass http://mywebapp-web:3000;
    }

    location /tasks {
        proxy_pass http://mywebapp-web:3000;
    }

    location / {
        proxy_pass http://mywebapp-web:3000;
    }
}
